gems: [jekyll-paginate]

# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            weroll
tagline:          'A Node.js Framework'
description:      'Build Your Micro-Service System Fast and Less Codes.'
url:              https://github.com/jayliang701/weroll
baseurl:          /

author:
  name:           'MagicFish Ltd. Inc.'
  url:            http://www.magicfish.cn/

paginate:         5

# Custom vars
version:          1.0.10

repository:       https://github.com/jayliang701/weroll

kramdown:
  input: GFM
  hard_wrap: false