gems: [jekyll-paginate]

# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            weroll
# tagline:          'An useful infrastructure of Node.js Application'
description:      'Build Your Micro-Service System Fast and Less Codes.'
url:              https://github.com/Snoopyjoy/ecoweb
baseurl:          https://snoopyjoy.github.io/ecoweb/

author:
  name:           'MagicFish Ltd. Inc.'
  url:            http://www.magicfish.cn/

paginate:         5

# Custom vars
version:          1.5.4

repository:       https://github.com/Snoopyjoy/ecoweb

kramdown:
  input: GFM
  hard_wrap: false
